require('dotenv').config({ path: 'd:/MARIOT/backend/.env' });
const mysql = require('mysql2/promise');

const brandsWithAbout = [
    { name: "3MF", about: "A highly reliable brand known for producing high-quality dry store and kitchen storage solutions. 3MF specializes in durable, food-grade shelving, modular storage systems, and heavy-duty organizational infrastructure that form the backbone of efficient commercial kitchens and pantries. Their meticulous attention to material strength and hygiene standards ensures that their products can withstand the rigorous demands of high-volume storage, making them a preferred choice for large-scale catering operations, hotels, and mass production facilities seeking to optimize their workspace and maintain strict sanitary compliance." },
    { name: "ALTO-SHAAM", about: "Founded in 1955 by Jerry Maahs, Alto-Shaam pioneered the revolutionary Halo Heat® technology, which uses low-density thermal cables to provide gentle, precise, and evenly distributed heat. They are a world leader in Cook & Hold ovens, smokers, heated holding cabinets, and advanced multi-cook chilling solutions. Dedicated to maximizing food quality and reducing shrinkage, Alto-Shaam's equipment allows chefs to prepare food ahead of time and hold it perfectly for hours without drying out or overcooking. Their relentless innovation continues to shape the commercial foodservice industry globally." },
    { name: "Anfim", about: "Born in Milan over 50 years ago, Anfim is dedicated exclusively to the art and science of espresso grinding. They manufacture premium, handmade grinders designed explicitly for professional baristas and high-end cafes. Known for their robust Italian engineering, heavy-duty motors, and highly precise titanium burrs, Anfim ensures consistent dosing, minimal heat generation, and unparalleled flavor extraction. Trusted in barista championships, Anfim remains a symbol of classic Italian coffee tradition blended meticulously with modern performance needs." },
    { name: "APW Wyott", about: "With a rich heritage spanning several decades, APW Wyott is a leading supplier of innovative and highly dependable commercial cooking and warming equipment. Their comprehensive product line includes heavy-duty conveyor toasters, hot dog rollers, soup warmers, griddles, and holding stations. Designed for maximum throughput and longevity, APW Wyott's solutions are absolutely essential for fast-paced quick-service restaurants, convenience stores, and institutional cafeterias that demand high performance and reliable heat distribution around the clock." },
    { name: "ASAKI", about: "Asaki is internationally renowned for providing exceptionally durable and efficient food processing equipment. Their robust product line features heavy-duty meat mincers, bone saws, vegetable prep machines, slicers, and planetary mixers. Engineered to withstand the rigorous demands of busy commercial kitchens, high-volume butcheries, and medium-scale food production facilities, Asaki emphasizes operator safety, ease of cleaning, and raw mechanical power to drastically reduce manual labor and prep times." },
    { name: "BERJAYA", about: "A comprehensive and dominant provider of commercial food service equipment, Berjaya offers an incredibly vast range of products encompassing heavy-duty commercial refrigeration, bakery deck ovens, display showcases, and custom stainless steel fabrication. Based in Malaysia, they are a one-stop-shop brand highly trusted across Asia, the Middle East, and beyond, celebrated for delivering reliable, cost-effective, and robust catering solutions that suit both small cafes and massive hotel kitchens." },
    { name: "blendtec", about: "Famous for their highly powerful and technologically advanced commercial blenders, Blendtec is the preferred choice of top international beverage chains. By inventing the square blending jar and employing ultra-thick blunt safety blades spinning at extreme velocities, Blendtec machines are designed to obliterate ice, frozen fruit, and tough ingredients. Their blenders produce the smoothest smoothies, frappes, and purees in seconds, supported by programmable cycles for perfect consistency every single time." },
    { name: "BREMA", about: "Since 1985, the Italian experts at Brema have been designing and manufacturing premium commercial ice-making machines with uncompromising standards. With a relentless focus on material quality, water efficiency, and environmental sustainability, Brema produces crystal-clear ice cubes, flakes, and pebbles. Their advanced spray and auger systems are essential for upscale cocktail bars, fine dining restaurants, fish markets, and medical facilities globally that demand pristine, slow-melting ice." },
    { name: "CAMRY", about: "Camry offers a specialized wide range of highly reliable kitchen appliances focused primarily on precision measurement and essential home-style commercial tools. They are particularly well-regarded in the industry for their highly accurate digital portion control scales, mechanical scales, and timing devices. These precision instruments are absolutely indispensable for recipe consistency, strict cost management, and quality control in commercial bakeries, ghost kitchens, and fine dining prep stations." },
    { name: "capinox", about: "Capinox provides top-grade, custom stainless steel fabrication meticulously tailored for demanding commercial kitchen environments. Their bespoke worktables, deep-basin sinks, high-extraction exhaust hoods, and modular shelving units are constructed exclusively using high-grade AISI 304 stainless steel. This commitment to premium materials ensures absolute hygiene, flawless rust resistance, and unyielding structural integrity under the punishing conditions of heavy daily culinary operations." },
    { name: "COFRIMELL", about: "Based in Rome, Cofrimell has been a global leader in manufacturing high-quality commercial cold beverage dispensers and slush (granita) machines since 1981. Their visually appealing, high-capacity cooling systems feature robust polycarbonate bowls, powerful compressors, and intuitive controls. They are staple, highly profitable equipment in cafes, hotels, convenience stores, and amusement parks worldwide, designed to attract impulse purchases through clear, vibrant display." },
    { name: "Desmon", about: "Desmon is a premier European specialist in professional commercial refrigeration, advanced blast chillers, and large-scale modular cold rooms. They utilize highly advanced high-density polyurethane insulation and incredibly energy-efficient refrigeration compressors. Their precision-engineered equipment is vital for rapid, safe food preservation, extending shelf life, and strict HACCP compliance in elite restaurant settings, massive catering events, and high-end hotel chains." },
    { name: "Electrolux", about: "Electrolux Professional is a global powerhouse delivering complete, fully integrated, and highly intelligent solutions for professional kitchens and commercial laundries. Known for deeply pioneering sustainable technologies, their premium combi ovens, rapid boiling pans, and high-efficiency rack-type dishwashers are designed for ultimate operational performance. They dramatically lower running costs through reduced water, energy, and detergent consumption while maximizing output." },
    { name: "EMPERO", about: "Empero is a massive and leading Turkish manufacturer of heavy-duty commercial kitchen setups. Operating from state-of-the-art production facilities, they manufacture virtually everything for a professional kitchen, from robust industrial gas cooking ranges and convection ovens to incredibly advanced flight-type dishwashing systems. They uniquely combine stringent European manufacturing quality standards with highly competitive pricing and rapid global distribution." },
    { name: "FAGOR", about: "Part of the massive ONNERA Group, Fagor Professional delivers advanced commercial cooking lines, commercial refrigeration, and heavy-duty warewashing equipment globally. Their equipment is heavily characterized by robust Spanish engineering, smart digital touchscreen controls, and a very strong focus on green energy and water efficiency. Fagor provides scalable solutions that can outfit a small tapas bar or a massive stadium catering facility." },
    { name: "Frymaster", about: "Founded in 1935, Frymaster is the undisputed, gold-standard in the industry for commercial deep fryers. They revolutionized the culinary world with the open-pot fryer design and highly advanced built-in oil filtration systems. Today, their high-efficiency, digitally controlled fryers are trusted exclusively by the world's largest fast-food chains to deliver perfectly crispy, uniform food while saving millions of dollars globally on oil usage." },
    { name: "Hamilton Beach", about: "Trusted worldwide for well over a century, Hamilton Beach Commercial specializes in incredibly high-performance culinary blenders, drink mixers, and beverage equipment. Their durable, high-torque motors and patented wave-action blending systems continually force ingredients down into the blades. This makes their heavy-duty equipment an absolute, unbreakable necessity for busy cocktail bars, global smoothie shop franchises, and high-prep commercial kitchens." },
    { name: "Hatco", about: "Since 1950, Hatco has been the foremost innovator and expert in holding, warming, and visually displaying food products. Their highly innovative decorative heat lamps, thermostatically controlled heated shelves, and powerful booster water heaters ensure that prepared food is kept safely at optimum serving temperatures. Crucially, Hatco engineering guarantees this heat retention without ever compromising food quality, texture, or drying it out before serving." },
    { name: "HENNY PENNY", about: "Henny Penny is world-famous for inventing the first commercial pressure fryer in 1957, a technological leap that forever revolutionized the fast-food chicken industry. Today, their incredibly advanced pressure fryers, high-volume open fryers, and smart heated holding cabinets form the highly reliable backbone of rapid, large-scale fried chicken and protein production for top-tier global restaurant and supermarket franchises." },
    { name: "KITCHENAID", about: "An iconic, deeply respected American brand established in 1919, KitchenAid Commercial delivers highly premium planetary mixers and heavy-duty culinary tools. Known for their timeless, classic aesthetic and practically indestructible all-metal-gear construction, their commercial mixers offer unmatched torque and reliability. They remain beloved and heavily relied upon by professional pastry chefs, artisanal bakers, and top culinary schools worldwide." },
    { name: "LA MARZOCCO", about: "Founded in 1927 in Florence, Italy, La Marzocco stands as the absolute gold standard in handmade, premium commercial espresso machines. They proudly pioneered the horizontal boiler and dual-boiler systems, dramatically changing coffee extraction. Today, their iconic, hand-assembled machines—like the legendary Linea Classic and the advanced Strada—are the beloved centerpieces of the world's absolute finest specialty coffee shops and roasteries." },
    { name: "LA CIMBALI", about: "With an illustrious history spanning over 100 years, La Cimbali represents the absolute pinnacle of traditional Italian espresso culture and engineering. They are unparalleled pioneers in high-end traditional espresso machines, super-automatic cappuccino machines, and patented thermal balancing systems. Their massive, beautiful machines are specifically designed to deliver exceptional coffee quality consistently, even at incredibly high, non-stop volumes." },
    { name: "MENUMASTER", about: "A prestigious brand falling under the ACP umbrella, Menumaster leads the global industry in massive-duty, high-speed commercial microwave ovens and accelerated cooking solutions. Their heavy-duty, stainless steel microwaves are over-engineered specifically to withstand hundreds of rigorous uses per day. They provide rapid, perfectly even heating which is absolutely crucial for maintaining speed-of-service in busy quick-service restaurants." },
    { name: "MERRYCHEF", about: "Merrychef has completely revolutionized the modern culinary landscape with its unmatched, ultra-high-speed accelerated cooking ovens. By ingeniously combining microwave, convection, and finely tuned air impingement technologies in a single compact footprint, their ovens can cook, toast, and bake food up to 20 times faster than conventional methods, making them the ultimate solution for intense, fast-casual dining environments." },
    { name: "nuova SIMONELLI", about: "Nuova Simonelli is an incredibly prestigious Italian company deeply embedded in the specialty coffee world, frequently serving as the highly esteemed official sponsor of the World Barista Championship. Their cutting-edge espresso machines are globally celebrated for their exceptional thermal stability, incredibly ergonomic barista-focused design, and advanced, scientific extraction technologies that push the boundaries of coffee flavor." },
    { name: "PITCO", about: "For over 100 years, Pitco has set the ultimate standard in commercial frying equipment engineering. Renowned for their bomb-proof robust construction and highly efficient tube-fired heating systems, Pitco fryers offer blisteringly rapid temperature recovery times. With advanced built-in oil filtration systems and massive output capacities, they easily handle the most demanding, high-volume kitchen environments on earth." },
    { name: "RANCILIO", about: "Founded in 1927, Rancilio is a highly respected and historically significant Italian manufacturer of incredibly durable, consistent professional espresso machines and commercial flat-burr grinders. Their heavy-duty equipment is highly prized worldwide for its straightforward, bulletproof engineering, incredibly easy maintenance, and its unrelenting ability to produce excellent, traditional espresso shots year after demanding year." },
    { name: "RATIONAL", about: "Rational is the undisputed, dominant world market leader in commercial combi-steam ovens and advanced intelligent cooking systems. Having invented the combi-steamer in 1976, their latest iCombi Pro ovens utilize highly advanced AI, responsive sensors, and precise climate management to automatically roast, bake, grill, and steam with perfect, reproducible precision, effectively replacing vast amounts of traditional, space-consuming kitchen equipment." },
    { name: "robot coupe", about: "The prestigious French pioneer and true inventor of the food processor, Robot Coupe utterly leads the global industry in dynamic food preparation equipment. Their immensely powerful vegetable prep machines, robust bowl cutters, and heavy-duty stick blenders are found in virtually every professional kitchen on the planet, saving chefs countless hours of manual labor with their razor-sharp precision and unmatched motor torque." },
    { name: "UNOX", about: "Unox is renowned globally for engineering highly innovative, intelligent, and technologically advanced commercial baking and gastronomy combi ovens. Driven heavily by data science and IoT connectivity, Unox ovens deliver masterfully precise humidity control, dynamic bi-directional air circulation, and perfectly even cooking results, empowering large-scale bakeries and elite restaurants to scale their menus flawlessly." },
    { name: "VITAMIX", about: "Vitamix Commercial remains the ultimate, unrivaled choice for high-end, professional blending. Known for their unmatched, ultra-high-horsepower motors, custom-designed aircraft-grade stainless steel blades, and legendary durability, they can completely pulverize whole ingredients into the smoothest purees, hot soups, and frozen beverages, making them indispensable workhorses in fine dining kitchens and specialized cocktail bars." },
    { name: "VULCAN", about: "Vulcan is a deeply historic, premier American manufacturer of heavy-duty, ultra-reliable commercial cooking equipment. Known for uncompromising master craftsmanship and raw power, their extensive line includes robust cast-iron gas ranges, high-capacity griddles, convection ovens, and massive steam kettles, providing the hot, beating heart required by countless, high-volume restaurant and institutional kitchens." },
    { name: "Zumex", about: "With over 35 years of dedicated innovation, Zumex is the global frontrunner in the design and manufacturing of beautiful, automatic commercial citrus juicers. Their deeply iconic and highly visual squeezing systems are uniquely engineered to extract maximum juice yield without ever crushing the bitter rind, consistently providing the freshest, sweetest, highest-quality juice for luxury hotels, premium supermarkets, and health-focused juice bars." }
];

(async () => {
    let conn;
    try {
        conn = await mysql.createConnection({
            host: process.env.DB_HOST,
            user: process.env.DB_USER,
            password: process.env.DB_PASS,
            database: process.env.DB_NAME
        });

        // 1. Check if column exists, if not, create it
        const [columns] = await conn.query("SHOW COLUMNS FROM brands LIKE 'description'");
        if (columns.length === 0) {
            console.log("Adding description column to brands table...");
            await conn.query("ALTER TABLE brands ADD COLUMN description TEXT");
        }

        // 2. Update brands
        for (const brand of brandsWithAbout) {
            console.log(`Updating brand: ${brand.name}`);
            const [result] = await conn.query('UPDATE brands SET description = ? WHERE name COLLATE utf8mb4_general_ci LIKE ?', [brand.about, `%${brand.name}%`]);
            if (result.affectedRows === 0) {
                console.log(`Brand not found by exact match: ${brand.name}, trying broader match.`);
                const [result2] = await conn.query('UPDATE brands SET description = ? WHERE name COLLATE utf8mb4_general_ci LIKE ?', [brand.about, `%${brand.name.split(' ')[0]}%`]);
                if (result2.affectedRows > 0) {
                    console.log(`Updated ${brand.name} via broader match.`);
                } else {
                    console.error(`Could not update description for ${brand.name}`);
                }
            } else {
                console.log(`Successfully updated ${brand.name}`);
            }
        }
        console.log("Finished updating brands.");

    } catch (err) {
        console.error(err);
    } finally {
        if (conn) await conn.end();
    }
})();
