require('dotenv').config({ path: 'd:/MARIOT/backend/.env' });
const mysql = require('mysql2/promise');

const missingBrands = [
    { name: "EASYLINE", about: "Easyline by Fimar offers a diverse range of reliable, cost-effective light commercial equipment. Designed perfectly for small cafes, kiosks, and home businesses, their product line includes planetary mixers, induction hobs, and vacuum packers that deliver professional results without the industrial price tag." },
    { name: "GG F", about: "GGF is a specialized Italian manufacturer globally recognized for producing highly robust equipment tailored for pizzerias and bakeries. Their high-heat electric deck ovens, powerful spiral dough mixers, and precision dough rollers are engineered to create authentic, perfect crusts and handle heavy, continuous daily use." },
    { name: "ACE FILTERS", about: "Ace Filters provides premium filtration technology specifically designed for commercial deep fryers. Their highly efficient filter papers and powders drastically extend the life of cooking oil by capturing microscopic burn particles, resulting in beautifully fried food, massive cost savings, and improved environmental impact." },
    { name: "fimar", about: "For over 40 years, Fimar has been a cornerstone of the Italian food processing industry. They manufacture incredibly sturdy meat mincers, bone saws, pasta machines, and robust vegetable cutters. Their heavy-duty equipment is a mandatory workhorse in busy butcheries, deli counters, and traditional Italian restaurant kitchens." },
    { name: "GEL MATIC", about: "Gel Matic is a sophisticated Italian brand completely dedicated to the engineering of express blending and freezing technologies. Their advanced soft-serve ice cream, frozen yogurt, and milkshake machines are famous for extraordinary reliability, huge hourly yields, and producing exceptionally smooth, creamy textures." },
    { name: "GHS", about: "GHS (Global Hospitality Solutions) is known for supplying highly durable and reliable food processing and storage equipment. Their products are thoroughly designed to withstand the tough environments of professional kitchens across the Middle East, delivering solid performance and excellent value for catering businesses." },
    { name: "HCONVED", about: "Hoonved (often listed under various spellings) is an esteemed Italian manufacturer specializing entirely in high-end commercial warewashing. From rapid glasswashers for busy cocktail bars to massive rack-conveyor dishwashers for hospitals, their machines are engineered for flawless hygiene, water conservation, and absolute reliability." },
    { name: "IMESA", about: "Imesa is a leading European name in professional and industrial laundry equipment. They manufacture highly advanced, heavy-duty washing machines, tumble dryers, and flatwork ironers. Driven by smart touchscreens and energy-efficient water cycles, Imesa systems are heavily trusted by luxury hotels, cruise ships, and commercial laundromats." },
    { name: "IMPERIAL", about: "Imperial Commercial Cooking Equipment is an iconic, heavy-duty American brand. Famous for their incredibly durable cast-iron grates and high-BTU burners, Imperial supplies massive gas ranges, convection ovens, and deep fryers that form the indestructible cooking backbone of huge steakhouses and high-volume diners." },
    { name: "INFRICO", about: "Infrico is Spain's absolute market leader in the commercial refrigeration sector. They specialize in high-quality refrigerated display cases, cold prep tables, and massive reach-in freezers. Infrico utilizes highly advanced, environmentally friendly refrigerants and incredibly deep insulation to guarantee perfect cold bridging and food safety." },
    { name: "JOSPER", about: "Josper completely modernized the ancient art of charcoal cooking by combining an oven and a grill in a single machine. Universally beloved by Michelin-star chefs and premium steakhouses, Josper ovens operate at extreme temperatures using 100% charcoal, delivering an unmatched, incredibly rich smoky flavor and perfect sear." },
    { name: "La Minerva", about: "La Minerva (Minerva Omega Group) is an incredibly prestigious Italian manufacturer of meat and food processing machinery. Their heavy-duty meat grinders, huge bandsaws, hamburger pressers, and slicers are a testament to legendary mechanical engineering, heavily relied upon by industrial butcheries and large-scale meat packers." },
    { name: "Longoni", about: "Longoni is an Italian specialist in the art of refrigerated display. They manufacture exquisitely designed, towering vertical glass showcases specifically for pastry shops, gelaterias, and premium wine cellars. Their cabinets combine flawless cooling technology with elegant lighting to dramatically boost impulse sales." },
    { name: "mac.pan", about: "MacPan is a specialized Italian brand dedicated entirely to the heavy-duty machinery required by industrial bakeries and large pizzerias. Their massive spiral mixers, automated dough dividers, and complex baguette molders are precision-engineered to process enormous quantities of dough with absolute consistency." },
    { name: "MAHLKONIG", about: "Mahlkönig is heavily regarded as the 'King of Grinders' in the specialty coffee industry. Handcrafted in Germany, their grinders (like the iconic EK43) feature massive, precision-engineered flat burrs that provide the most even particle distribution in the world, making them mandatory in championship-level coffee shops." },
    { name: "MARIOT", about: "Mariot is our incredibly proud, specialized house brand. Deeply understanding the heavy demands of Middle Eastern kitchens, Mariot produces a highly reliable range of cost-effective, heavy-duty kitchen equipment, from high-heat cooking ranges to durable refrigeration solutions, all backed by our exceptional local warranty." },
    { name: "MARIOT FABRICATION", about: "Mariot Fabrication is our specialized, bespoke stainless steel division. We employ master welders and heavy-gauge AISI 304 stainless steel to custom-build entirely bespoke exhaust hoods, deep-basin sinks, workbenches, and structural shelving, perfectly tailored to the exact millimeter of your commercial kitchen space." },
    { name: "MBM", about: "MBM is a highly respected Italian manufacturer providing complete, modular cooking lines designed specifically for restaurants and large catering facilities. Part of the massive Eurotec group, their sleek, heavy-duty modular ranges allow chefs to seamlessly combine fryers, griddles, and pasta boilers into one beautiful, continuous cooking island." },
    { name: "Middleby Marshall", about: "Middleby Marshall is the undisputed world leader in commercial conveyor ovens. Their massive, high-speed impingement ovens are the absolute cornerstone of the global pizza delivery industry (including giants like Domino's and Papa John's), engineered to aggressively blast heat and bake hundreds of pizzas per hour with zero varying." },
    { name: "miska", about: "Miska Food Technology offers specialized heavy-duty processing solutions for demanding commercial environments. They build robust machinery aimed at simplifying bulk food preparation, providing durable planetary mixers and slicing solutions that reduce massive amounts of manual labor in busy cafeteria settings." },
    { name: "MKE-MATIC", about: "MKE is a highly dominant industrial kitchen brand hailing from Turkey, known for massive-scale capability. They operate enormous factories to produce everything from huge military-grade boiling kettles to expansive cold rooms, outfitting massive hotel infrastructures, hospitals, and industrial catering camps globally." },
    { name: "MOEL", about: "Mo-El is a highly specialized Italian brand focusing entirely on professional hygiene and immediate heating solutions. They are most famous globally for their highly effective, specialized UV insect killers and powerful electric infrared heaters, which are heavily utilized in outdoor luxury dining patios and hygienic food processing plants." },
    { name: "MONOLITH", about: "Monolith produces some of the most incredibly durable commercial plumbing fixtures in the industry. Their heavy-duty pre-rinse spray assemblies, specialized knee-operated sink valves, and massive commercial faucets are heavily over-engineered to withstand the absolute chaotic abuse of busy pot-washing stations." },
    { name: "OMEGA", about: "Omega is a highly prestigious brand within the Minerva Omega group, representing the absolute pinnacle of Italian food processing mechanics. Their stunningly crafted gravity meat slicers, massive electric cheese graters, and industrial vacuums are legendary for their terrifyingly sharp precision and decades-long durability." },
    { name: "oztiryakiler", about: "Oztiryakiler (often known as Ozti) is an absolute juggernaut in the commercial kitchen industry. Exporting from Turkey to over 100 countries, they manufacture a breathtakingly huge range of robust, heavy-duty equipment including massive combi ovens, flight dishwashers, and full modular cooking lines at highly competitive pricing." },
    { name: "POSLIX", about: "Poslix is a cutting-edge technology brand specializing entirely in advanced, highly responsive Point of Sale (POS) hardware. Their incredibly sleek, spill-resistant touchscreen terminals and rapid thermal receipt printers form the digital nervous system of modern, fast-paced restaurants and sprawling retail supermarkets." },
    { name: "PRINCE CASTLE", about: "Prince Castle is a deeply historic American brand famous for heavily optimizing the fast-food workflow. They focus on holding, high-speed toasting, and precise portion control. Their vertical contact toasters and dedicated holding bins are actively used by the largest burger chains on earth to ensure immediate, hot food delivery." },
    { name: "RED FOX", about: "Red Fox is the smart, highly strategic commercial brand of the massive RM Gastro group. They deliver a comprehensive range of incredibly durable, no-nonsense tabletop cooking equipment. Their heavy iron griddles, contact grills, and deep fryers are the unbreakable workhorses of busy food trucks and heavy-volume diners." },
    { name: "ROLLER GRILL", about: "As Europe's absolute leading manufacturer of specialized commercial cooking equipment, Roller Grill boasts the largest range of countertop machines in the world. Their crepe makers, heavy waffle irons, massive rotisseries, and hot dog rollers are engineered for non-stop, intense daily production in heavily trafficked kiosks and cafes." },
    { name: "ROTONDI", about: "Rotondi Group is an incredibly high-tech Italian manufacturer specializing primarily in massive, industrial garment care and pressing machinery. While highly prevalent in commercial dry cleaning, their incredibly powerful steam generators and heavy-duty ironing boards are heavily utilized in huge 5-star hotel laundry operations." },
    { name: "SAB", about: "SAB Italia is a highly specialized artisan manufacturer of traditional espresso coffee machines. Handcrafted near Milan, SAB machines prioritize a deeply authentic, traditional mechanical aesthetic paired with incredibly heavy, highly thermally stable E61 brewing groups, delivering intensely rich, classic Italian espresso." },
    { name: "samixir", about: "Samixir is a specialized Turkish manufacturer dominating the market for cold beverage dispensing. Their high-capacity stirred juice dispensers and incredibly chilling slush machines feature massive, indestructible bowls and aggressive cooling compressors, designed explicitly to thrive and perform in extreme summer heat environments." },
    { name: "SANTOS", about: "Santos is an incredibly prestigious French manufacturer with a 65-year history of building the world's finest commercial juicers and coffee grinders. Known for their whisper-quiet, incredibly high-torque induction motors, Santos machines are the absolute gold standard for high-end juice bars and luxury hotel breakfast buffets globally." },
    { name: "SAP", about: "SAP is a highly specialized, heavy-industry Italian manufacturer of incredibly powerful meat processing machinery. Their massive stainless steel bone saws and huge commercial meat mincers are heavily relied upon by industrial slaughterhouses, massive fish markets, and extremely high-volume commercial butcheries." },
    { name: "SHEFFIELD", about: "Sheffield provides robust, straightforward commercial refrigeration and heavy-duty food preparation equipment. Focusing heavily on exceptional value and unyielding reliability, Sheffield commercial freezers and preparation tables are highly popular choices for cost-conscious startups, busy food trucks, and medium-scale catering businesses." },
    { name: "SOFINOR", about: "Sofinor is a celebrated French manufacturer specializing heavily in the fabrication of premium stainless steel kitchen furniture and catering equipment. From highly specialized rotisseries to perfectly hygienic, knee-operated hand wash basins, Sofinor guarantees incredibly refined French engineering and flawless sanitary compliance." },
    { name: "SOUTHBEND", about: "Southbend is a deeply iconic, heavyweight American manufacturer of premium commercial cooking equipment. For over a century, their terrifyingly powerful blast-convection ovens, heavy-duty broilers, and massive cast-iron restaurant ranges have defined the high-volume, aggressive cooking environment of America's finest steakhouses." },
    { name: "SPACEMAN", about: "Spaceman is a highly innovative global leader in the manufacturing of incredibly powerful soft serve ice cream and frozen beverage machines. Their massive, dual-hopper machines utilize patented freezing cylinders to deliver insanely high hourly output of perfectly smooth ice cream, vastly outperforming extremely expensive competitors." },
    { name: "Speed Queen", about: "Speed Queen is the undisputed, absolute legend of the commercial laundry industry. Manufactured in America, their massively over-engineered washing machines and huge tumble dryers are famous for lasting literally decades. They are the unbreakable, heavy-metal backbone of commercial laundromats and massive multi-housing facilities globally." },
    { name: "STAR", about: "Star Manufacturing is a cornerstone American brand producing incredibly heavy-duty commercial cooking equipment. Their massive cast-iron griddles, terrifyingly fast conveyor toasters, and highly durable panini presses are the absolute, unbreakable foundation of busy 24/7 diners, delis, and high-volume sandwich chains." },
    { name: "TOASTMASTER", about: "Toastmaster is a legendary, deeply historic brand that literally invented the pop-up toaster in the 1920s. Today, under the massive Middleby corporation, they manufacture highly rugged, heavy-duty countertop cooking equipment, including hot plates and griddles, built exactly to survive extremely punishing commercial environments." },
    { name: "UNION", about: "Union is an Italian industrial juggernaut and the absolute global leader in the highly complex dry cleaning machinery sector. Their incredibly massive, highly advanced dry cleaning plants utilize complex, computerized solvent recovery systems, making them an absolute necessity for enormous, industrial-scale high-end garment care operations." },
    { name: "SERVER", about: "Server Products is a highly specialized American manufacturer dominating the condiment and portion-control dispensing market. Their heavy-duty, stainless steel pump dispensers and specialized food warmers ensure exact, measured portions of hot fudge, cheese, and sauces, heavily optimizing food costs for massive global fast-food chains." },
    { name: "STILCO", about: "Stilco provides incredibly rugged, no-nonsense commercial catering equipment designed for heavy, practical utility. Their specialized shawarma machines, huge electric fryers, and high-capacity food warmers are incredibly popular among fast-food kiosks and massive cafeterias that demand absolute reliability under constant abuse." },
    { name: "TECHNOCOOLER", about: "Technocooler specializes entirely in highly advanced commercial refrigeration and huge cold storage solutions. Utilizing incredibly efficient compressors and deep polyurethane insulation, they manufacture massive chilled display cabinets and deep freezers that are critical for preserving vast amounts of inventory in supermarkets and massive dark kitchens." },
    { name: "TECNODOM", about: "Tecnodom is an enormous Italian manufacturing giant producing incredibly massive quantities of commercial refrigeration and stainless steel equipment. They offer exceptional European build quality—manufacturing specialized pizza prep counters, huge blast chillers, and massive upright freezers—at incredibly aggressive, highly competitive global price points." },
    { name: "UEBERMILK", about: "Ubermilk is a highly advanced, ultra-innovative German brand that completely solved the biggest bottleneck in specialty coffee: milk frothing. Their incredibly advanced, automated milk frothers perfectly steam and texture hundreds of liters of milk per hour with zero varying, allowing baristas to focus entirely on espresso extraction and customer service." },
    { name: "BATTISTELLA", about: "Battistella is a highly specialized Italian manufacturer dominating the professional wet cleaning and heavy ironing sector. Their incredibly powerful, high-pressure industrial steam generators and massive, heated vacuum ironing boards are completely essential for high-end boutique dry cleaners and massive 5-star hotel luxury garment care." },
    { name: "BILAIT", about: "Bilait specializes incredibly heavily in producing professional-grade, high-volume chocolate and specialized confectionery equipment. Their highly advanced tempering machines and massive hot chocolate dispensers feature incredibly precise, constant temperature control, ensuring massive amounts of chocolate perfectly retain their gloss, snap, and crystalline structure." },
    { name: "VITO", about: "Vito is a revolutionary German manufacturer that radically changed commercial frying. Their highly advanced, drop-in oil filtration systems aggressively suck up and micro-filter frying oil directly in the hot vat. By massively clearing out microscopic carbon, Vito systems drastically double the life of expensive cooking oil, saving massive restaurants absolute fortunes." },
    { name: "Zemic", about: "Zemic is a massive, highly advanced global powerhouse in the production of highly precise load cells and strain gauges. While rarely seen by consumers, their incredibly accurate, heavy-duty sensors form the hyper-accurate, calculating brains behind the world's most advanced digital commercial scales and massive industrial weighing systems." },
    { name: "Ailipu", about: "Ailipu is a highly specialized manufacturer focusing incredibly heavily on advanced, high-power commercial induction cooking technologies. Their massive commercial induction hobs and huge electric wok cookers provide terrifyingly fast, deeply intensive heat transfer, replacing massive, dangerous gas installations in modern, high-tech commercial kitchens." },
    { name: "Bimatic", about: "Bimatic is an incredibly respected Italian manufacturer specializing entirely in the complex edge-banding and specialized woodworking machinery sector. Within the hospitality space, their massive, highly precise machinery is utilized globally to construct completely flawless, incredibly durable commercial bar counters, massive hotel reception desks, and robust kitchen cabinetry." },
    { name: "Bunn", about: "Bunn-O-Matic is an absolute, legendary titan of the American coffee industry. Having invented the flat-bottom coffee filter, Bunn today manufactures incredibly advanced, indestructible high-volume batch brewers and massive hot water towers. They are the absolute, unquestioned backbone of hot beverage delivery for global diners, massive chain restaurants, and huge hotels." },
    { name: "Grindmaster", about: "Grindmaster (now Grindmaster-Cecilware) is a deeply historic American manufacturer with absolute mastery over commercial beverage dispensing. They produce incredibly massive, high-volume coffee grinders, huge hot water urns, and terrifyingly efficient cold beverage bubblers, designed specifically to operate continuously in extremely high-traffic massive cafeterias." },
    { name: "Hoshizaki", about: "Hoshizaki is a legendary, massive Japanese corporation and generally considered the absolute pinnacle of commercial ice-making engineering globally. Known for their terrifying precision, Hoshizaki machines employ an incredibly unique, massive closed-cell water system to produce absolutely flawless, incredibly hard, perfectly pure ice cubes that simply refuse to melt quickly." },
    { name: "Mussana", about: "Mussana is a highly specialized German manufacturer widely considered to build the absolute greatest cream whipping machines on planet earth. Using an incredibly advanced, highly guarded internal micro-labyrinth system, Mussana machines transform liquid cream into an incredibly dense, extremely voluminous structure impossible to achieve by hand or blender." },
    { name: "Pastaline", about: "Pastaline is an incredibly specialized Italian manufacturer completely dedicated to the ancient art of dough processing. Their massive, highly advanced dough sheeters, extremely aggressive spiral mixers, and specialized pasta extruders bring absolute, unquestioned industrial efficiency to the deeply traditional creation of fresh, authentic Italian pasta and massive pizzas." },
    { name: "Salva", about: "Salva is a massive, highly prestigious Spanish manufacturer of incredibly advanced, heavy-duty commercial bakery equipment. Their enormous rotary rack ovens, deeply insulated modular deck ovens, and heavy volumetric dough dividers are universally trusted by massive industrial bakeries and large supermarkets globally to continuously produce flawless, artisanal breads." },
    { name: "Snooker", about: "Snooker specializes incredibly heavily in producing highly cost-effective, extremely rugged commercial ice making machines. Highly popular strongly across the massive Asian and Middle Eastern markets, Snooker provides incredibly reliable, heavy-duty ice production for very busy restaurants, large juice bars, and massive fish displays at highly competitive price points." },
    { name: "Turbo Chef", about: "TurboChef (a massive Middleby brand) completely invented and dominates the absolute pinnacle of the rapid-cook oven industry. Using terrifyingly advanced microwaves and incredibly aggressive jets of super-heated impinged air, TurboChef ovens can literally cook a completely raw pizza or deeply toast a sandwich perfectly in a shocking 60 seconds." },
    { name: "Venarro", about: "Venarro is a highly aggressive, rapidly expanding manufacturer of heavy-duty commercial kitchen equipment. Based heavily in Turkey, Venarro produces incredibly durable, massive industrial cooking ranges, huge convection ovens, and exceptionally robust stainless steel handling equipment designed to easily survive the incredible abuse of massive industrial catering." },
    { name: "Venix", about: "Venix is a deeply innovative, highly advanced Italian manufacturer specializing entirely in high-tech commercial ovens and massive blast chillers. Driven incredibly heavily by smart, touchscreen technology and elegant Italian design, Venix combi-ovens deliver perfectly precise humidity and aggressive heat control for sophisticated hotel banqueting and massive bakeries." },
    { name: "Warning", about: "Waring Commercial (often misspelled as Warning) is an absolute legend of the American culinary industry, notoriously famous for having introduced the absolute very first blender in America. Today, their incredibly terrifying, heavy-duty food processors, massive stick blenders, and huge waffle makers are completely indestructible fixtures in commercial kitchens globally." },
    { name: "Zmatik", about: "Zmatik is an incredibly specialized Italian manufacturing powerhouse focusing absolutely entirely on heavy-duty pastry and bakery processing. Their massive, floor-standing reversible dough sheeters, huge croissant rolling machines, and absolutely massive planetary mixers are heavily relied upon by massive industrial pastry plants to continuously fold and sheet perfect dough flawlessly." }
];

(async () => {
    let conn;
    try {
        conn = await mysql.createConnection({
            host: process.env.DB_HOST,
            user: process.env.DB_USER,
            password: process.env.DB_PASS,
            database: process.env.DB_NAME
        });

        for (const brand of missingBrands) {
            console.log(`Updating brand: ${brand.name}`);
            const [result] = await conn.query('UPDATE brands SET description = ? WHERE name COLLATE utf8mb4_general_ci LIKE ?', [brand.about, `%${brand.name}%`]);
            if (result.affectedRows === 0) {
                console.log(`Brand not found by exact match: ${brand.name}, trying broader match.`);
                const [result2] = await conn.query('UPDATE brands SET description = ? WHERE name COLLATE utf8mb4_general_ci LIKE ?', [brand.about, `%${brand.name.split(' ')[0]}%`]);
                if (result2.affectedRows > 0) {
                    console.log(`Updated ${brand.name} via broader match.`);
                } else {
                    console.error(`Could not update description for ${brand.name}`);
                }
            } else {
                console.log(`Successfully updated ${brand.name}`);
            }
        }
        console.log("Finished updating missing brands.");

    } catch (err) {
        console.error(err);
    } finally {
        if (conn) await conn.end();
    }
})();
